version: "3"
services:
  nextjs:
    image: muhammadusama7/cscfinder:latest
    ports:
      - 3000:3000
    depends_on:
      - mongodb
#    volumes:
#      - .:/app
# from build server
#    environment:
#      - DATABASE_URL=mongodb://myadmin:myadmin@mongodb:27017/mydb

  mongodb:
    image: mongo
    restart: always
    env_file:
      - ${COMPOSE_ENV_FILE}

    volumes:
#      - mongodb_data:/data/db
      - ./mongodb-init.sh:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017

volumes:
  mongodb_data:
