version: "3"
services:
  nextjs:
    image: muhammadusama7/cscfinder:latest
    ports:
      - 3000:3000
    depends_on:
      - mongodb
#    volumes:
#      - .:/app
# from build server
#    environment:
#      - MONGODB_URL=mongodb://admin:admin@mongodb:27017/mydb

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myadmin
      MONGO_INITDB_ROOT_PASSWORD: myadmin
      MONGO_INITDB_DATABASE: mydb
#    volumes:
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017





  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://myadmin:myadmin@mongodb:27017/mydb
    depends_on:
      - nextjs
#volumes:
#  mongodb_data:
