version: '3'

services:

  nginx:
    container_name: nginx-con
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nextjs-nginx.conf:/etc/nginx/conf.d/nextjs-nginx.conf
      - nginx-conf:/etc/nginx
    networks:
      - appnet
    restart: always

volumes:
  nginx-conf:

networks:
  appnet:

