version: "3"
services:
  nextjs:
    image: muhammadusama7/cscfinder:latest
    ports:
      - 3000:3000
    depends_on:
      - mongodb
#    volumes:
#      - .:/app
# from build server
#    environment:
#      - DATABASE_URL=mongodb://myadmin:myadmin@mongodb:27017/mydb

  mongodb:
    image: mongo
    restart: always
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_CREDENTIALS.username}
#      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_CREDENTIALS.password}
#      - MONGO_INITDB_DATABASE==${MONGODB_CREDENTIALS.database}
#      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
#      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
#      MONGO_INITDB_DATABASE: $MONGODB_DATABASE
    env_file:
      - ${COMPOSE_ENV_FILE}

    volumes:
#      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017

volumes:
  mongodb_data:
